### PR TITLE
modifications to help get this working

### PR DESCRIPTION
**Pull request by adamthiede**
Hello, if you remember you emailed me a while back about distributing my little launcher program with this. The launcher program still isn't that good, but your work here is! I'm interested in helping getting this working. This isn't complete and isn't working yet, but figured I'd just open this draft and let you know. The SDL dependencies seem to be the biggest obstacle, at least for me.
Cheers!

### CODE REVIEW

**Comment by adamthiede** [comment]
So I guess I don't need to build SDL2* as submodules, the SDK has them. But how to get it to recognize that is the next hurdle I guess?

```
[📦 org.freedesktop.Sdk ~]$ find / -iname '*sdl*net*'
find: ‘/proc/tty/driver’: Permission denied
/usr/lib/x86_64-linux-gnu/libSDL2_net-2.0.so.0.200.0
/usr/lib/x86_64-linux-gnu/libSDL2_net-2.0.so
/usr/lib/x86_64-linux-gnu/libSDL2_net.so
/usr/lib/x86_64-linux-gnu/cmake/SDL2_net
/usr/lib/x86_64-linux-gnu/cmake/SDL2_net/SDL2_net-shared-targets.cmake
/usr/lib/x86_64-linux-gnu/cmake/SDL2_net/SDL2_netConfigVersion.cmake
/usr/lib/x86_64-linux-gnu/cmake/SDL2_net/SDL2_netConfig.cmake
/usr/lib/x86_64-linux-gnu/cmake/SDL2_net/SDL2_net-shared-targets-noconfig.cmake
/usr/lib/x86_64-linux-gnu/libSDL2_net-2.0.so.0
/usr/include/SDL2/SDL_net.h
/usr/share/cmake-3.24/Modules/FindSDL_net.cmake
/usr/share/licenses/SDL2_net
```

**Comment by adamthiede** [comment]
Okay, I think it works now! Flatpaks for the 3 games, based on this code, are working.

`flatpak remote-add alephone https://elagost.com/flatpak/repo_alephone.flatpakrepo` to add the remote, if you'd like to test. I have no idea how to submit these to flathub, if you would be OK with that.

**Comment by slembcke** [comment]
Oh, neat. I'll have to check this out tomorrow maybe.

> The launcher program still isn't that good, but your work here is!

Heh, I appreciate the sentiment, but I just read some docs and put together a build script. I do enjoy that we can both build on the shoulders of a larger project though. :) Honestly it looks like you put at least as much effort into understanding the Flatpak stuff as I have. I never tried making a repo for example. As for Flathub, I forget the details, but it sounds like instead of submitting a binary, you send a pull request to get your git repository added to a list of packages they build on their own infrastructure.

In other news, the Aleph maintainer also just asked to merge my build scripts in to the main repository? So... maybe he's going to start publishing a Flatpak or pushing to Flathub? I dunno? -> https://github.com/Aleph-One-Marathon/alephone/issues/344#issuecomment-1304972692

Not quite sure what the next move would be then, I guess we could poke him on Discord and see what's up.

**Comment by adamthiede** [comment]
Thanks for the quick response. Glad we both more-or-less have the same goal in mind.

I figured the flathub business was just 'ask to get this repo pulled into github.com/flathub/ somehow', but if the project's actual maintainers are gonna do it, all the better.

**Comment by adamthiede** [comment]
I've updated my branch to use extra-data and (theoretically) download the datafiles at install time. The run.sh script extracts the data to the flatpak's data dir and runs the game using that. I don't think you can extract extra-data from the flatpak into itself, since it's read-only.

Since the flatpak no longer distributes the game data, just the engine, and the data is downloaded by the user at install time, this should get around the legal issues, right?

**Comment by slembcke** [comment]
I finally got around to checking this out today. >_> Everything seemed to build fine, but I got this error at the end:

```
 5. [✗] org.lhowon.alephone.marathon1             master            i       marathon1-origin      0 bytes

Error: Extra data missing in detached metadata
error: Failed to install bundle org.lhowon.alephone.marathon1: Extra data missing in detached metadata
```

Anyway, you've been putting in a lot of time on this, and I'm just holding things up. I added you as a contributor so I can get out of your way. I could transfer the repository to you or make a "Marathon Flatpak" organization too if that sounds preferable.

**Comment by adamthiede** [comment]
Thank you! I appreciate the invitation. I'll make sure things build before merging. If you'd rather have it in an organization, that's fine, but I don't at all mind it being under your account.

**Comment by adamthiede** [comment]
It's probably because the `build-bundle` command doesn't support extra-data. I'm using extra-data because of the legal distribution issues surrounding the [game data](https://github.com/Aleph-One-Marathon/data-marathon).

I assume the flatpaks can be built to a local repository, and installed that way.

**Comment by adamthiede** [comment]
```
$ flatpak create-usb /tmp/m1usb org.lhowon.alephone.marathon1
error: Installed ref ‘app/org.lhowon.alephone.marathon1/x86_64/master’ is extra-data, and cannot be distributed offline
```

`create-usb`, the other offline option, also fails with `extra-data`.

However I'm not sure there's much point to this since the upstream maintainers are bundling their own flatpak releases now; [the .flatpak files provided here](https://github.com/Aleph-One-Marathon/alephone/releases/tag/release-20230119) can be downloaded and installed and they work well.

The only reason to employ `extra-data` would be for third-party distribution, like Flathub.

**Comment by slembcke** [comment]
Oooh interesting yeah. I tried installing the .flatpack file directly. I assumed that would still be able to do the external data thing. Hrm.

**Comment by adamthiede** [comment]
Well, at the very least I got [this launcher thing](https://git.sr.ht/~elagost/alephone-launcher) into a state where it can be built as a flatpak bundle, and installed that way. (Since it downloads files itself, it sidesteps both the legal issues and `extra-data` trouble.)

It's still not a piece of software I'm all that proud of, but it works!

**Pull request closed without merging**
